[package]
name = "leptonic"
version = "0.0.1"
edition = "2021"
rust-version = "1.56"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptonic"
description = """
The Leptos component library.
"""
categories = ["gui"]
keywords = ["leptos", "components"]

[dependencies]
indexmap = "1"
js-sys = "0.3"
leptos = { version = "0.3", default-features = false, features = [
    "csr",
    "serde",
    "tracing",
] }
leptos-icons = { git = "https://github.com/lpotthast/leptos-icons", branch = "enum", features = [
    "csr",
    "BsSun",
    "BsMoon",
    "BsCheckCircleFill",
    "BsCaretUp",
    "BsCaretUpFill",
    "BsCaretDown",
    "BsCaretDownFill",
] }
leptos_router = { version = "0.3", default-features = false, features = [
    "csr",
] }
serde = "1"
serde-wasm-bindgen = "0.5"
serde_json = "1"
time = { version = "0.3", features = [
    "wasm-bindgen",
    "macros",
    "serde",
    "serde-well-known",
] }
tracing = "0.1"
uuid = { version = "1", features = ["v4", "v7", "js", "serde"] }
wasm-bindgen = "0.2"
# TODO: What of all below is really required?
web-sys = { version = "0.3", features = ["Storage", "HtmlInputElement", "Event", "EventTarget", "HtmlFormElement"] }

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = "0.3"
