[package]
name = "leptonic"
version = "0.0.2"
edition = "2021"
rust-version = "1.56"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lpotthast/leptonic"
description = """
The Leptos component library.
"""
categories = ["gui"]
keywords = ["leptos", "components", "component-library"]

[dependencies]
indexmap = "1"
js-sys = "0.3"
leptos = { version = "0.4", features = ["csr"] }
leptos_icons = { git = "https://github.com/Carlosted/leptos-icons", branch = "main", default-features = false, features = [
#leptos_icons = { version = "0.0.15", features = [
    "BsSun",
    "BsMoon",
    "BsCheckCircleFill",
    "BsInfoCircleFill",
    "BsExclamationCircleFill",
    "BsExclamationTriangleFill",
    "BsCaretUp",
    "BsCaretUpFill",
    "BsCaretDown",
    "BsCaretDownFill",
    "BsParagraph",
    "BsTypeBold",
    "BsTypeItalic",
    "BsTypeStrikethrough",
    "BsBlockquoteLeft",
    "BsBrightnessAltHigh",
    "BsTextLeft",
    "BsTextCenter",
    "BsTextRight",
    "BsJustify",
    "BsXCircleFill",
] }
leptos-tiptap = "0.2"
leptos-use = { version = "0.4", features = ["math"] }
leptos_router = "0.4"
serde = "1"
serde-wasm-bindgen = "0.5"
serde_json = "1"
strum = { version = "0.25.0", features = ["derive"] }
time = { version = "0.3", features = [
    "wasm-bindgen",
    "macros",
    "serde",
    "serde-well-known",
] }
tracing = "0.1"
uuid = { version = "1", features = ["v4", "v7", "js", "serde"] }
wasm-bindgen = "0.2"
# TODO: What of all below is really required?
web-sys = { version = "0.3", features = [
    "DomRect",
    "Event",
    "EventTarget",
    "HtmlFormElement",
    "HtmlInputElement",
    "Storage",
] }

[dev-dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3"
web-sys = "0.3"
