[package]
name = "book"
version = "0.1.0"
edition = "2021"
build = false

[[bin]]
name = "force-build"
path = "build.rs"
required-features = ["build_deps"]  # only needed for build-dependencies

[profile.release]
opt-level = "s"
lto = "thin"
debug = 0

[dependencies]
leptos = { version = "0.2", default-features = false, features = ["csr", "tracing"] }
leptos_meta = { version = "0.2", default-features = false, features = ["csr"] }
leptos_router = { version = "0.2", default-features = false, features = [
    "csr",
] }
leptos-icons = { git = "https://github.com/lpotthast/leptos-icons", branch = "enum", features = [
    "csr",
    "BsFolder",
    "BsFolderFill",
] }
leptonic = { path = "../.." }
leptonic-theme = { path = "../../../leptonic-theme", optional = true }
console_error_panic_hook = "0.1"
console_log = "1"
log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
serde = "1"
serde-wasm-bindgen = "0.5"
serde_json = "1"
time = { version = "0.3", features = ["wasm-bindgen"] }
uuid = { version = "1", features = ["js", "v4", "v7", "serde"] }
wasm-bindgen = "0.2"

[features]
build_deps = ["leptonic-theme"]
