[package]
name = "book"
version = "0.1.0"
edition = "2021"
build = false

[[bin]]
name = "force-build"
path = "build.rs"
required-features = ["build_deps"] # only needed for build-dependencies

[profile.release]
opt-level = "z"
lto = "thin"
debug = 0

[dependencies]
console_error_panic_hook = "0.1"
console_log = "1"
indoc = "2.0.1"
leptonic = { path = "../../leptonic" }
leptonic-theme = { path = "../../leptonic-theme", optional = true }
leptos = { version = "0.3", default-features = false, features = [
    "csr",
    "tracing",
    "stable",
] }
leptos-icons = { git = "https://github.com/lpotthast/leptos-icons", branch = "enum", features = [
    "csr",
    "BsGithub",
    "BsFolder",
    "BsFolderFill",
    "BsBook",
    "BsColumnsGap",
    "BsToggles",
    "BsChatSquare",
    "BsCircleSquare",
    "BsArrowsMove",
] }
leptos-tiptap-build = { git = "https://github.com/lpotthast/leptos-tiptap", branch = "main", optional = true }
leptos_meta = { version = "0.3", default-features = false, features = [
    "csr",
    "stable",
] }
leptos_router = { version = "0.3", default-features = false, features = [
    "csr",
    "stable",
] }
log = "0.4"
serde = "1"
serde-wasm-bindgen = "0.5"
serde_json = "1"
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["js", "v4", "v7", "serde"] }
wasm-bindgen = "0.2"

[features]
build_deps = ["leptonic-theme", "leptos-tiptap-build"]
