[package]
name = "book"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[profile.release]
opt-level = "z"
lto = "thin"
debug = 0

[dependencies]
console_error_panic_hook = "0.1"
console_log = "1"
indoc = "2.0.1"
leptonic = { path = "../../leptonic" }
leptos = { version = "0.4", features = ["csr"] }
leptos_icons = { git = "https://github.com/Carlosted/leptos-icons", branch = "main", default-features = false, features = [
#leptos_icons = { version = "0.0.15", features = [
    "BsGithub",
    "BsSearch",
    "BsList",
    "BsThreeDots",
    "BsFolder",
    "BsFolderFill",
    "BsBook",
    "BsColumnsGap",
    "BsToggles",
    "BsChatSquare",
    "BsCircleSquare",
    "BsArrowsMove",
] }
leptos-use = { git = "https://github.com/lpotthast/leptos-use", branch = "leptos_0.4" }
leptos_meta = { version = "0.4", features = [
    "csr",
] }
leptos_router = { version = "0.4", features = [
    "csr",
] }
log = "0.4"
serde = "1"
serde-wasm-bindgen = "0.5"
serde_json = "1"
strum = { version = "0.25", features = ["derive"] }
time = { version = "0.3", features = ["wasm-bindgen"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["js", "v4", "v7", "serde"] }
wasm-bindgen = "0.2"

[build-dependencies]
leptonic-theme = { path = "../../leptonic-theme" }
leptos-tiptap-build = "0.2"
